version: "3.7"

volumes:
  static:

services:
  django:
    build:
      context: .
      dockerfile: ./commpose/production/django/Dockerfile
    volumes:
      - static:/static
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django
